spring.application.name=e-m-s

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_management_system
spring.datasource.username=postgres
spring.datasource.password=JPvirat@2005

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=EMS-JWT-Secret-Key-2026-Only-For-Development-123456789
# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
